version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: yarn run start:dev
    networks:
      - webnet
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - webnet
networks:
  webnet:
